version: '2'
services:
  couchdb:
    image: apache/couchdb
    ports:
      - "5984:5984"
    networks:
      dbs:
        aliases:
          - couchdb

  couchdb-lucene:
    image: klaemo/couchdb-lucene
    ports:
      - "5985:5985"
    networks:
      dbs:
        aliases:
          - couchdb-lucene

networks:
  dbs:
    driver: bridge
